import { writeFileSync } from 'node:fs'
import pkg from './package.json' with { type: 'json' }

const props = JSON.stringify(
  Object.fromEntries(
    Object.entries(pkg.contributes.configuration.properties)
      .map(([key, value]) => value.enum
        ? [key, `'${value.enum.join('\' | \'')}'`]
        : [key, value.type],
      ),
  ),
  null,
  2,
)
  .replace(/: "([^"]*)",?/g, (_, $1) => `: ${$1}`)
  .replace(/codeimg\./g, '')
  .replace(/integer/g, 'number')
  .replace(/"/g, '')

writeFileSync('./types/config.ts', `// auto generated by \`node config.mjs\`, don't edit manually

export type Config = ${props}
`)
