// auto generated by `node config.mjs`, don't edit manually

export type Config = {
  background: string
  boxShadow: 'small' | 'medium' | 'large'
  containerPadding: string
  debounce: boolean
  roundedCorners: string
  scale: number
  format: 'jpg' | 'png' | 'svg' | 'webp'
  showWindowControls: boolean
  windowControlsColor: boolean
  showWindowTitle: boolean
  showLineNumbers: boolean
}
