// auto generated by `node config.mjs`, don't edit manually

export type Config = {
  background: string
  boxShadow: 'small' | 'medium' | 'large'
  containerPadding: string
  roundedCorners: string
  scale: number
  showWindowControls: boolean
  showWindowTitle: boolean
  showLineNumbers: boolean
}
